### ISSUE TITLE
Latest docker image isn't working

### ISSUE THREAD

**Issue by ssfinney** [ngineered/boinc-container#1]
Hi! I've been enjoying using Boinc on docker, but the latest container image isn't working for me. I forked the repo and published the same image from your Dockerfile and it's working!

Just FYI. Not sure why your latest didn't work on my Mac.

Thanks for publishing this image!

**Comment by richarvey** [comment]
sorry i missed this will take a look

**Comment by richarvey** [comment]
should be fixed now
